// Predefined library of common cosmetic ingredients with their INCI names and types.
// Used to auto-fill ingredient details when a known name is selected.

export const INGREDIENT_LIBRARY = {
  'Aloe Vera Inner Leaf Gel 1:1 Decolorized': { inci: 'Aloe Barbadensis Leaf Juice', type: 'Humectant' },
  'Neem Powder': { inci: 'Azadirachta Indica (Neem) Leaf Powder', type: 'Powder' },
  'Rose Petal Powder': { inci: 'Rosa Centifolia (Rose) Petal Powder', type: 'Powder' },
  'Shikakai Powder': { inci: 'Acacia Concinna (Shikakai) Fruit Powder', type: 'Powder' },
  'Baking Soda': { inci: 'Sodium Bicarbonate', type: 'Other' },
  'Butter: Aloe Vera': { inci: 'Cocos Nucifera (Coconut) Oil and Aloe Barbadensis Leaf Extract', type: 'Butter' },
  'Butter: Coffee Bean': { inci: 'Hydrogenated Vegetable Oil, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Coffea Arabica (Coffee) Seed Oil', type: 'Butter' },
  'Butter: Cupuacu': { inci: 'Theobroma Grandiflorum (Cupuacu) Seed Butter', type: 'Butter' },
  'Butter: Mango': { inci: 'Mangifera Indica (Mango) Seed Butter', type: 'Butter' },
  'Butter: Murumuru': { inci: 'Astrocaryum Murumuru Seed Butter', type: 'Butter' },
  'Butter: Shea, Pressed and Refined': { inci: 'Butyrospermum Parkii (Shea Butter) Fruit', type: 'Butter' },
  'Citric Acid': { inci: 'Citric Acid', type: 'Active' },
  'Clay: Bentonite': { inci: 'Bentonite', type: 'Clay' },
  'Clay: French Black': { inci: 'Montmorillonite (Terra Black Clay)', type: 'Clay' },
  'Clay: French Green': { inci: 'Montmorillonite (French Green Clay)', type: 'Clay' },
  'Clay: Green Illite': { inci: 'Illite (Clay)', type: 'Clay' },
  'Clay: Kaolin, Coral': { inci: 'Kaolin (and) Red Iron Oxide', type: 'Clay' },
  'Clay: Kaolin, White': { inci: 'Kaolin (White Clay)', type: 'Clay' },
  'Clay: Multani Mitti': { inci: 'Solum Fullonum (Fuller\'s Earth)', type: 'Clay' },
  'Clay: Red Illite': { inci: 'Illite (Clay)', type: 'Clay' },
  'Clay: Rhassoul': { inci: 'Moroccan Lava Clay', type: 'Clay' },
  'Clay: Rose': { inci: 'Kaolin (White Clay) (and) Iron Oxide', type: 'Clay' },
  'Clay: Sea': { inci: 'Kaolinite', type: 'Clay' },
  'Clay: Yellow Illite': { inci: 'Illite (Clay)', type: 'Clay' },
  'CO2 Extract: Arnica Flower Total': { inci: 'Helianthus Annuus Seed Oil (and) Arnica Montana Flower Extract', type: 'Extract' },
  'CO2 Extract: Calendula Total': { inci: 'Calendula Officinalis (Flower) Extract', type: 'Extract' },
  'CO2 Extract: Cardamom Select': { inci: 'Elettaria Cardamomum (Cardamom) Extract', type: 'Extract' },
  'CO2 Extract: Carrot Root Total': { inci: 'Helianthus Annuus (Sunflower) Seed Oil and Daucus Carota (Carrot) Root Extract and Rosmarinus Officinalis (Rosemary) Leaf Extract', type: 'Extract' },
  'CO2 Extract: Chamomile, German Total': { inci: 'Chamomilla Recutita (Blue Chamomile) Flower Extract', type: 'Extract' },
  'CO2 Extract: Clove Bud Select': { inci: 'Syzygium Aromaticum (Clove) Bud Extract', type: 'Extract' },
  'CO2 Extract: Cocoa Select': { inci: 'Theobroma Cacao (Cocoa) Extract', type: 'Extract' },
  'CO2 Extract: Frankincense Select': { inci: 'Boswellia Carteri (Frankincense) Extract', type: 'Extract' },
  'CO2 Extract: Lavender Bud Select': { inci: 'Lavandula Angustifolia (Lavender) Flower Extract', type: 'Extract' },
  'CO2 Extract: Myrrh Select': { inci: 'Commiphora Myrrha (Myrrh) Resin Extract', type: 'Extract' },
  'CO2 Extract: Oregano Select': { inci: 'Origanum Vulgare (Oregano) Leaf Extract', type: 'Extract' },
  'CO2 Extract: Sandalwood Select, Indian': { inci: 'Santalum Album (Sandalwood) Extract', type: 'Extract' },
  'CO2 Extract: Sea Buckthorn Berry Total': { inci: 'Hippophae Rhamnoides (Sea Buckthorn) Fruit Extract', type: 'Extract' },
  'CO2 Extract: Tomato Seed Total': { inci: 'Solanum Lycopersicum (Tomato) Seed Extract', type: 'Extract' },
  'CO2 Extract: Vanilla, 12% Vanillin': { inci: 'Vanilla Planifolia (Vanilla) Fruit Extract', type: 'Extract' },
  'Color Additive: Aqua Green': { inci: 'Hydrated Chromium Oxide', type: 'Colorant' },
  'Color Additive: Black Oxide': { inci: 'Iron Oxides', type: 'Colorant' },
  'Color Additive: Chromium Oxide Green': { inci: 'Chromium Oxide', type: 'Colorant' },
  'Color Additive: Manganese Violet': { inci: 'Manganese Violet', type: 'Colorant' },
  'Color Additive: Titanium Dioxide, Oil Dispersible': { inci: 'Titanium Dioxide', type: 'Colorant' },
  'Color Additive: Ultramarine Blue (Dark)': { inci: 'Ultramarine', type: 'Colorant' },
  'Color Additive: Yellow Oxide': { inci: 'Iron Oxides', type: 'Colorant' },
  'Coral Calcium Powder': { inci: 'Coral', type: 'Powder' },
  'Essential Oil: Allspice, Jamaica': { inci: 'Pimenta Officinalis (Allspice) Oil', type: 'Essential Oil' },
  'Essential Oil: Angelica Root': { inci: 'Angelica Archangelica Root Oil', type: 'Essential Oil' },
  'Essential Oil: Cajeput': { inci: 'Melaleuca Cajuputi (Cajeput) Oil', type: 'Essential Oil' },
  'Essential Oil: Carrot Seed': { inci: 'Daucus Carota (Carrot) Seed Oil', type: 'Essential Oil' },
  'Essential Oil: Chamomile, German': { inci: 'Matricaria Recutita (German Chamomile) Flower Oil', type: 'Essential Oil' },
  'Essential Oil: Cinnamon Bark': { inci: 'Cinnamomum Burmannii (Cinnamon) Bark Oil', type: 'Essential Oil' },
  'Essential Oil: Citronella (Java Type)': { inci: 'Cymbopogon Winterianus Leaf Oil', type: 'Essential Oil' },
  'Essential Oil: Clary Sage': { inci: 'Salvia sclarea (Clary) Oil', type: 'Essential Oil' },
  'Essential Oil: Eucalyptus Globulus': { inci: 'Eucalyptus Globulus Oil', type: 'Essential Oil' },
  'Essential Oil: Geranium': { inci: 'Pelargonium Graveolens (Geranium) Oil', type: 'Essential Oil' },
  'Essential Oil: Ginger, Fresh Sweet': { inci: 'Zingiber Officinale (Ginger) Oil', type: 'Essential Oil' },
  'Essential Oil: Grapefruit, Pink': { inci: 'Citrus Paradisi (Grapefruit) Oil', type: 'Essential Oil' },
  'Essential Oil: Lavender, Bulgarian': { inci: 'Lavandula Angustifolia (Lavender) Oil', type: 'Essential Oil' },
  'Essential Oil: Lemon Tea Tree': { inci: 'Leptospermum Petersonii (Lemon Tea Tree) Oil', type: 'Essential Oil' },
  'Essential Oil: Lime, Persian': { inci: 'Citrus Latifolia (Lime) Oil', type: 'Essential Oil' },
  'Essential Oil: Melissa (Lemon Balm)': { inci: 'Melissa Officinalis (Lemon Balm) Oil', type: 'Essential Oil' },
  'Essential Oil: Neroli': { inci: 'Citrus Aurantium (Neroli) Oil', type: 'Essential Oil' },
  'Essential Oil: Orange, Sweet': { inci: 'Citrus Sinensis (Sweet Orange) Oil', type: 'Essential Oil' },
  'Essential Oil: Palo Santo': { inci: 'Bursera Graveolens (Palo Santo) Wood Oil', type: 'Essential Oil' },
  'Essential Oil: Patchouli, Light': { inci: 'Pogostemon Cablin (Patchouli) Oil', type: 'Essential Oil' },
  'Essential Oil: Peppermint': { inci: 'Mentha Piperita (Peppermint) Oil', type: 'Essential Oil' },
  'Essential Oil: Rosemary Cineole': { inci: 'Rosmarinus Officinalis (Rosemary) Oil', type: 'Essential Oil' },
  'Essential Oil: Sandalwood, Indian': { inci: 'Santalum Album (Sandalwood) Oil', type: 'Essential Oil' },
  'Essential Oil: Spearmint': { inci: 'Mentha Spicata (Spearmint) Oil', type: 'Essential Oil' },
  'Essential Oil: Tangerine': { inci: 'Citrus Reticulata (Tangerine) Oil', type: 'Essential Oil' },
  'Essential Oil: Tea Tree': { inci: 'Melaleuca Alternifolia (Tea Tree) Leaf Oil', type: 'Essential Oil' },
  'Essential Oil: Vetiver': { inci: 'Vetiveria Zizanioides (Vetiver) Root Oil', type: 'Essential Oil' },
  'Essential Oil: Yuzu': { inci: 'Citrus Junos (Yuzu) Oil', type: 'Essential Oil' },
  'Exfoliant: Bamboo Powder': { inci: 'Bambusa Arundinacea (Banslochan) Powder', type: 'Exfoliant' },
  'Exfoliant: Pumice Powder': { inci: 'Pumice', type: 'Exfoliant' },
  'Exfoliant: Rice Husk Powder': { inci: 'Oryza Sativa (Rice) Husk Powder', type: 'Exfoliant' },
  'Exfoliant: Tagua Seed Powder': { inci: 'Phytelephas Aequatorialis (Tagua) Seed Powder', type: 'Exfoliant' },
  'Floral Wax: Gardenia': { inci: 'Gardenia Jasminoides (Gardenia) Wax', type: 'Wax' },
  'Floral Wax: Jasmine Grandiflorum': { inci: 'Jasminum Grandiflorum (Jasmine) Wax', type: 'Wax' },
  'Floral Wax: Jasmine Sambac': { inci: 'Jasminum Sambac (Jasmine) Wax', type: 'Wax' },
  'Floral Wax: Magnolia': { inci: 'Michelia Alba (Magnolia) Wax', type: 'Wax' },
  'Floral Wax: Osmanthus': { inci: 'Osmanthus Fragrans (Osmanthus) Wax', type: 'Wax' },
  'Floral Wax: Pink Lotus': { inci: 'Nelumbo Nucifera (Pink Lotus) Wax', type: 'Wax' },
  'Floral Wax: Rose Centifolia': { inci: 'Rosa Centifolia (Rose) Wax', type: 'Wax' },
  'Floral Wax: Tuberose': { inci: 'Polianthes Tuberosa (Tuberose) Wax', type: 'Wax' },
  'Glycerin, USP (vegetable)': { inci: 'Glycerin', type: 'Humectant' },
  'Grain Products: Colloidal Oat Flour, Fine': { inci: 'Avena Sativa (Oat) Kernel Flour', type: 'Powder' },
  'Grain Products: Corn Starch': { inci: 'Zea Mays (Corn) Starch', type: 'Powder' },
  'Grain Products: Rice Bran Powder': { inci: 'Oryza Sativa (Rice) Bran', type: 'Powder' },
  'Herb: Arrowroot Powder': { inci: 'Maranta arundinacea', type: 'Botanical' },
  'Herb: Green Tea Leaf Powder': { inci: 'Camellia Sinensis (Green Tea) Leaf', type: 'Botanical' },
  'Herb: Juniper Berries': { inci: 'Juniperus Communis (Juniper) Berries', type: 'Botanical' },
  'Herb: Lavender Buds': { inci: 'Lavandula Angustifolia (Lavender) Buds', type: 'Botanical' },
  'Herb: Nettles, Stinging, Powder': { inci: 'Urtica Dioica (Stinging Nettles) Leaf Powder', type: 'Botanical' },
  'Herb: Sandalwood, Indian, Powder': { inci: 'Santalum Album (Sandalwood) Powder', type: 'Botanical' },
  'Herb: Spearmint Leaf': { inci: 'Mentha Spicata (Spearmint) Leaf', type: 'Botanical' },
  'Honey Powder': { inci: 'Maltodextrin (and) Honey', type: 'Powder' },
  'Hydrosol: Witch Hazel': { inci: 'Hamamelis Virginiana (Witch Hazel) Distillate (and) Benzoic Acid', type: 'Hydrosol' },
  'Magnesium Chloride Flakes': { inci: 'Magnesium Chloride', type: 'Active' },
  'Mica Powder': { inci: 'Mica', type: 'Powder' },
  'Milk Powder: Buttermilk': { inci: 'Buttermilk Powder', type: 'Powder' },
  'Milk Powder: Goats Milk': { inci: 'Whole Dry Goat Milk', type: 'Powder' },
  'Milk Powder: Whole': { inci: 'Whole Dry Milk', type: 'Powder' },
  'Mud: Dead Sea': { inci: 'Maris Limus Extract (Sea Silt Extract)', type: 'Clay' },
  'Mud: Dead Sea Powder': { inci: 'Maris Limus (Dead Sea Mud)', type: 'Clay' },
  'Nut Shell: Almond Shell Powder': { inci: 'Prunus Amygdalus Dulcis (Almond) Shell Powder', type: 'Exfoliant' },
  'Nut Shell: Walnut Shell Powder': { inci: 'Juglans Regia (Walnut) Shell Powder', type: 'Exfoliant' },
  'Oil: Abyssinian': { inci: 'Crambe Abyssinica (Abyssinian) Seed Oil', type: 'Oil' },
  'Oil: Acai Berry Pulp, Virgin': { inci: 'Euterpe Oleracea (Acai) Pulp Oil', type: 'Oil' },
  'Oil: Andiroba, Virgin': { inci: 'Carapa Guianensis (Andiroba) Nut Oil', type: 'Oil' },
  'Oil: Apricot Kernel': { inci: 'Prunus Armeniaca (Apricot) Kernel Oil', type: 'Oil' },
  'Oil: Black Raspberry Seed, Virgin': { inci: 'Rubus Occidentalis (Black Raspberry) Seed Oil', type: 'Oil' },
  'Oil: Blackberry Seed, Virgin': { inci: 'Rubus Fruticosus (Blackberry) Seed Oil', type: 'Oil' },
  'Oil: Blackcurrant Seed': { inci: 'Ribes Nigrum (Blackcurrant) Seed Oil', type: 'Oil' },
  'Oil: Blueberry Seed, Virgin': { inci: 'Vaccinium Corymbosum (Blueberry) Seed Oil', type: 'Oil' },
  'Oil: Brazil Nut, Refined': { inci: 'Bertholletia Excelsa (Brazil) Nut Oil', type: 'Oil' },
  'Oil: Buriti Fruit, Refined': { inci: 'Mauritia Flexuosa (Buriti) Fruit Oil', type: 'Oil' },
  'Oil: Caprylic Capric Triglycerides (MCT Oil)': { inci: 'Caprylic/Capric Triglycerides', type: 'Oil' },
  'Oil: Carrot Seed Oil, Virgin': { inci: 'Daucus Carota Sativa (Carrot) Seed Oil', type: 'Oil' },
  'Oil: Castor': { inci: 'Ricinus Communis (Castor) Seed Oil', type: 'Oil' },
  'Oil: Coconut (RBD)': { inci: 'Cocos Nucifera (Coconut) Oil', type: 'Oil' },
  'Oil: Coffee, Roasted': { inci: 'Coffea arabica (Coffee) Seed Oil', type: 'Oil' },
  'Oil: Cranberry Seed': { inci: 'Vaccinium Macrocarpon (Cranberry) Seed Oil', type: 'Oil' },
  'Oil: Cucumber Seed, Virgin': { inci: 'Cucumis Sativus (Cucumber) Oil', type: 'Oil' },
  'Oil: Evening Primrose': { inci: 'Oenothera Biennis (Evening Primrose) Oil', type: 'Oil' },
  'Oil: Grape Seed, Virgin': { inci: 'Vitis Vinifera (Grape) Seed Oil', type: 'Oil' },
  'Oil: Hazelnut': { inci: 'Corylus Avellana (Hazel) Seed Oil', type: 'Oil' },
  'Oil: Hemp Seed, Refined': { inci: 'Cannabis Sativa (Hemp) Seed Oil', type: 'Oil' },
  'Oil: Jojoba, Natural': { inci: 'Simmondsia Chinensis (Jojoba) Seed Oil', type: 'Oil' },
  'Oil: Kukui Nut, RBD': { inci: 'Aleurites Moluccana (Kukui) Nut Oil', type: 'Oil' },
  'Oil: Macadamia Nut': { inci: 'Macadamia Ternifolia (Macadamia) Seed Oil', type: 'Oil' },
  'Oil: Maracuja (Passionfruit Seed)': { inci: 'Passiflora Incarnata (Passionfruit) Seed Oil', type: 'Oil' },
  'Oil: Marula': { inci: 'Sclerocarya Birrea (Marula) Kernel Oil', type: 'Oil' },
  'Oil: Meadowfoam Seed': { inci: 'Limnanthes Alba (Meadowfoam) Seed Oil', type: 'Oil' },
  'Oil: Moringa': { inci: 'Moringa Oleifera (Moringa) Seed Oil', type: 'Oil' },
  'Oil: Palm, Sustainable': { inci: 'Eleais Guineensis (Palm) Oil', type: 'Oil' },
  'Oil: Papaya Seed': { inci: 'Carica Papaya (Papaya) Seed Oil', type: 'Oil' },
  'Oil: Pomegranate Seed': { inci: 'Punica Granatum (Pomegranate) Seed Oil', type: 'Oil' },
  'Oil: Poppy Seed': { inci: 'Papaver Somniferum (Poppy) Seed Oil', type: 'Oil' },
  'Oil: Red Raspberry Seed': { inci: 'Rubus Idaeus (Red Raspberry) Seed Oil', type: 'Oil' },
  'Oil: Shea': { inci: 'Butyrospermum Parkii (Shea Butter) Extract', type: 'Oil' },
  'Oil: Squalane Olive': { inci: 'Squalane', type: 'Oil' },
  'Oil: Strawberry Seed': { inci: 'Fragaria Ananassa (Strawberry) Seed Oil', type: 'Oil' },
  'Oil: Tamanu (Foraha Oil)': { inci: 'Calophyllum Tacamahaca (Tamanu) Seed Oil', type: 'Oil' },
  'Oil: Vitamin E 400IU (Tocopherol)': { inci: 'Tocopherol', type: 'Oil' },
  'Oil: Watermelon Seed, Refined': { inci: 'Citrullus Lanatus (Watermelon) Seed Oil', type: 'Oil' },
  'Organic Butter: Cocoa': { inci: 'Theobroma Cacao (Cocoa) Butter', type: 'Butter' },
  'Organic Butter: Mango': { inci: 'Mangifera Indica (Mango) Seed Butter', type: 'Butter' },
  'Organic Butter: Shea, Refined': { inci: 'Butyrospermum Parkii (Shea) Butter', type: 'Butter' },
  'Organic CO2 Extract: Black Cumin Total': { inci: 'Nigella Sativa (Black Cumin) Seed Extract', type: 'Extract' },
  'Organic CO2 Extract: Calendula Total': { inci: 'Calendula Officinalis (Marigold) Flower Extract', type: 'Extract' },
  'Organic CO2 Extract: Chamomile, German, Total': { inci: 'Chamomilla Recutita (Chamomile) Flower Extract', type: 'Extract' },
  'Organic CO2 Extract: Rose Damascena Select': { inci: 'Rosa Damascena (Rose) Extract', type: 'Extract' },
  'Organic CO2 Extract: Vanilla, 12% Vanillin': { inci: 'Vanilla Planifolia (Vanilla) Fruit Extract', type: 'Extract' },
  'Organic Cocoa Powder': { inci: 'Theobroma Cacao (Cocoa) Seed Extract', type: 'Powder' },
  'Organic Essential Oil: Basil Linalool': { inci: 'Ocimum Basilicum (Basil) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Bergamot, FCF': { inci: 'Citrus Bergamia (Bergamot) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Cedarwood, Atlas': { inci: 'Cedrus Atlantica (Cedarwood) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Chamomile, Roman': { inci: 'Anthemis nobilis (Roman Chamomile) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Cinnamon Bark': { inci: 'Cinnamomum Zeylanicum (Cinnamon) Bark Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Clary Sage': { inci: 'Salvia sclarea (Clary Sage) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Clove Bud': { inci: 'Eugenia Caryophyllata (Clovebud) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Eucalyptus Globulus': { inci: 'Eucalyptus Globulus (Eucalyptus) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Frankincense': { inci: 'Boswellia Carteri (Frankincense) Gum Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Geranium, Rose': { inci: 'Pelargonium Graveolens (Geranium) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Grapefruit, Pink': { inci: 'Citrus Paradisi (Grapefruit) Peel Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Helichrysum Italicum': { inci: 'Helichrysum Italicum (Immortelle) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Lavender, Bulgarian': { inci: 'Lavandula Angustifolia (Lavender) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Lemon': { inci: 'Citrus Limon (Lemon) Peel Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Melissa (Lemon Balm)': { inci: 'Melissa Officinalis (Lemon Balm) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Myrrh': { inci: 'Commiphora myrrha (Myrrh) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Neroli': { inci: 'Citrus Aurantium (Neroli) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Orange, Sweet': { inci: 'Citrus Sinensis (Orange) Peel Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Palmarosa': { inci: 'Cymbopogon Martini (Palmarosa) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Peppermint': { inci: 'Mentha Piperita (Peppermint) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Rosemary Cineole': { inci: 'Rosmarinus Officinalis (Rosemary) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Spearmint': { inci: 'Mentha Spicata (Spearmint) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Tea Tree': { inci: 'Melaleuca Alterniflora (Tea Tree) Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Vetiver': { inci: 'Vetiveria Zizanoides (Vetiver) Root Oil', type: 'Essential Oil' },
  'Organic Essential Oil: Ylang Ylang Complete': { inci: 'Cananga Odorata (Ylang Ylang) Oil', type: 'Essential Oil' },
  'Organic Herb: Calendula Powder': { inci: 'Calendula Officinalis', type: 'Botanical' },
  'Organic Hydrosol: Calendula': { inci: 'Calendula Officinalis Distillate', type: 'Hydrosol' },
  'Organic Hydrosol: Cucumber': { inci: 'Cucumus Sativus (Cucumber) Distillate', type: 'Hydrosol' },
  'Organic Hydrosol: German Chamomile': { inci: 'Matricaria Chamomilla (German Chamomile) Distillate', type: 'Hydrosol' },
  'Organic Hydrosol: Lavender': { inci: 'Lavandula Angustifolia (Lavender) Distillate', type: 'Hydrosol' },
  'Organic Hydrosol: Rose Damascena': { inci: 'Rose Damascena Flower Water', type: 'Hydrosol' },
  'Organic Hydrosol: Rose Geranium': { inci: 'Pelargonium Graveolens (Rose Geranium) Distillate', type: 'Hydrosol' },
  'Organic Hydrosol: Rosemary': { inci: 'Rosmarinus Officinalis (Rosemary) Distillate', type: 'Hydrosol' },
  'Organic Lecithin: Soy Liquid': { inci: 'Lecithin', type: 'Emulsifier' },
  'Organic Lecithin: Sunflower Liquid': { inci: 'Lecithin', type: 'Emulsifier' },
  'Organic Menthol Crystals': { inci: 'Menthol', type: 'Active' },
  'Organic Oil: Almond, Sweet': { inci: 'Prunus Amygdalus Dulcis (Sweet Almond) Oil', type: 'Oil' },
  'Organic Oil: Apricot Kernel, Virgin': { inci: 'Prunus Armeniaca (Apricot) Kernel Oil', type: 'Oil' },
  'Organic Oil: Argan': { inci: 'Argania Spinosa (Argan) Kernel Oil', type: 'Oil' },
  'Organic Oil: Avocado': { inci: 'Persea Gratissima (Avocado) Oil', type: 'Oil' },
  'Organic Oil: Babassu': { inci: 'Orbignya Oleifera (Babassu) Seed Oil', type: 'Oil' }
};
